apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-bot-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
      app: fin-bot
  template:
    metadata:
      labels:
        app: fin-bot
    spec:
      containers:
      - name: bot
        image: bdistin/discord-bot-container:latest
        env:
        - name: BOT_TOKEN
          value: "$(BOT_TOKEN_FIN)"
          